In [2]:
#librerias a importar
import pandas as pd
import numpy as np

In [5]:
#Se importan los csv de cada uno de los departamentos
ALTA_VERAPAZ = pd.read_csv('ALTA_VERAPAZ.csv')
CIUDAD_CAPITAL = pd.read_csv('CIUDAD_CAPITAL.csv')
GUATEMALA = pd.read_csv('GUATEMALA.csv')

In [6]:
#Se concatenan todos los dataframes --- agregar los demas departamentos
df = pd.concat([ALTA_VERAPAZ], axis=0, ignore_index=True)

In [7]:
#Listamos los nombres de las columnas
list(df.keys())

#Borramos filas duplicadas
df=df.drop_duplicates()

In [13]:
#Observamos la cantidad de na de cada variable
print(df['CODIGO'].isna().sum())
print(df['DISTRITO'].isna().sum())
print(df['DEPARTAMENTO'].isna().sum())
print(df['MUNICIPIO'].isna().sum())
print(df['ESTABLECIMIENTO'].isna().sum())
print(df['DIRECCION'].isna().sum())
print(df['TELEFONO'].isna().sum())
print(df['SUPERVISOR'].isna().sum())
print(df['DIRECTOR'].isna().sum())
print(df['NIVEL'].isna().sum())
print(df['SECTOR'].isna().sum())
print(df['AREA'].isna().sum())
print(df['STATUS'].isna().sum())
print(df['MODALIDAD'].isna().sum())
print(df['JORNADA'].isna().sum())
print(df['PLAN'].isna().sum())
print(df['DEPARTAMENTAL'].isna().sum())

0
2
0
0
0
2
20
2
48
0
0
0
0
0
0
0
0

In [14]:
#Botamos todas las filas con valores nulos en el código o establecimiento
df=df.dropna(subset = ['CODIGO', 'ESTABLECIMIENTO'])

df

,CODIGO,DISTRITO,DEPARTAMENTO,MUNICIPIO,ESTABLECIMIENTO,DIRECCION,TELEFONO,SUPERVISOR,DIRECTOR,NIVEL,SECTOR,AREA,STATUS,MODALIDAD,JORNADA,PLAN,DEPARTAMENTAL
0,16-01-0138-46,16-031,ALTA VERAPAZ,COBAN,COLEGIO COBAN,KM.2 SALIDA A SAN JUAN CHAMELCO ZONA 8,77945104,MERCEDES JOSEFINA TORRES GALVEZ,JULIO CESAR VILLELA AMADO,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
1,16-01-0139-46,16-031,ALTA VERAPAZ,COBAN,COLEGIO PARTICULAR MIXTO VERAPAZ,KM 209.5 ENTRADA A LA CIUDAD,77367402,MERCEDES JOSEFINA TORRES GALVEZ,---,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
2,16-01-0140-46,16-031,ALTA VERAPAZ,COBAN,"COLEGIO ""LA INMACULADA""",7A. AVENIDA 11-109 ZONA 6,78232301,MERCEDES JOSEFINA TORRES GALVEZ,VIRGINA SOLANO SERRANO,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
3,16-01-0141-46,16-005,ALTA VERAPAZ,COBAN,ESCUELA NACIONAL DE CIENCIAS COMERCIALES,2A CALLE 11-10 ZONA 2,79514215,RUDY ADOLFO TOT OCH,NaN,DIVERSIFICADO,OFICIAL,URBANA,ABIERTA,MONOLINGUE,MATUTINA,DIARIO(REGULAR),ALTA VERAPAZ
4,16-01-0142-46,16-005,ALTA VERAPAZ,COBAN,INSTITUTO NORMAL MIXTO DEL NORTE 'EMILIO ROSAL...,3A AVE 6-23 ZONA 11,79521468,RUDY ADOLFO TOT OCH,NaN,DIVERSIFICADO,OFICIAL,URBANA,ABIERTA,BILINGUE,VESPERTINA,DIARIO(REGULAR),ALTA VERAPAZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,16-17-0120-46,16-017,ALTA VERAPAZ,RAXRUHA,INSTITUTO MIXTO DE EDUCACION BILINGUE INTERCUL...,BARRIO SANTA MARIA,58209425,FREDY OSWALDO TEYUL CHIQUIN,ROMULO EFREN QUIROA LUIS,DIVERSIFICADO,PRIVADO,URBANA,CERRADA TEMPORALMENTE,MONOLINGUE,DOBLE,FIN DE SEMANA,ALTA VERAPAZ
344,16-17-0123-46,16-026,ALTA VERAPAZ,RAXRUHA,INSTITUTO NACIONAL DE EDUCACION DIVERSIFICADA,BARRIO CONCEPCION,33530288,ILEANA VERÓNICA MACZ CALACH,JOSE MANUEL DE LA CRUZ RAMIREZ,DIVERSIFICADO,OFICIAL,URBANA,ABIERTA,MONOLINGUE,VESPERTINA,DIARIO(REGULAR),ALTA VERAPAZ
345,16-17-0143-46,16-050,ALTA VERAPAZ,RAXRUHA,CENTRO DE EDUCACIÓN EXTRAESCOLAR,RAXRUHÁ,48488623,MAXIMILIANO CHUB ICAL,EDGAR FLORENCIO TUT CHUB,DIVERSIFICADO,OFICIAL,URBANA,ABIERTA,MONOLINGUE,DOBLE,SEMIPRESENCIAL,ALTA VERAPAZ
346,16-17-0144-46,16-026,ALTA VERAPAZ,RAXRUHA,"INSTITUTO MIXTO DE MAGISTERIO BILINGÜE ""SAN AN...",BARRIO SANTA MARÍA,40659805,ILEANA VERÓNICA MACZ CALACH,MATEO COC CUC,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,DOBLE,FIN DE SEMANA,ALTA VERAPAZ
347,16-17-0147-46,16-026,ALTA VERAPAZ,RAXRUHA,"INSTITUTO MIXTO DE MAGISTERIO BILINGÜE ""SAN AN...",BARRIO SANTA MARIA,57533118,ILEANA VERÓNICA MACZ CALACH,MATEO COC CUC,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,SIN JORNADA,SEMIPRESENCIAL (FIN DE SEMANA),ALTA VERAPAZ

In [16]:
#Contamos las repeticiones de establecimientos
df.ESTABLECIMIENTO.value_counts()

INSTITUTO NACIONAL DE EDUCACION DIVERSIFICADA                  29
INSTITUTO NACIONAL DE EDUCACIÓN DIVERSIFICADA                   9
INSTITUTO MIXTO DE EDUCACION BILINGUE INTERCULTURAL -IMEBI-     7
COLEGIO MIXTO CIENCIAS TECNOLÓGICAS                             7
LICEO GALILEO GALILEI                                           6
                                                               ..
CENTRO EDUCATIVO SAN MATEO                                      1
INSTITUTO PRIVADO MIXTO PRIMARIA BILINGUE AJ KUTUNEL            1
CENTRO EDUCATIVO SAN MARTIN DE PORRES                           1
LICEO TECNOLÓGICO CAHABONCITO -LITEC-                           1
COLEGIO COBAN                                                   1
Name: ESTABLECIMIENTO, Length: 177, dtype: int64

In [18]:
#Removemos acentos
cols = df.select_dtypes(include=[object]).columns
df[cols] = df[cols].apply(lambda x: x.str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8'))
df.ESTABLECIMIENTO.value_counts()

INSTITUTO NACIONAL DE EDUCACION DIVERSIFICADA                  38
COLEGIO MIXTO CIENCIAS TECNOLOGICAS                             8
COLEGIO PRIVADO MIXTO TECNOLOGICO EN INFORMATICA                7
INSTITUTO MIXTO DE EDUCACION BILINGUE INTERCULTURAL -IMEBI-     7
COLEGIO PRIVADO MIXTO LA ENSENANZA                              6
                                                               ..
COLEGIO MIXTO EVANGELICO NAZARENO                               1
ESCUELA NORMAL DE EDUCACION FISICA                              1
INSTITUTO GUATEMALTECO DE EDUCACION RADIOFONICA (IGER)          1
LICEO DE COMPUTACION Y EDUCACION PARA EL HOGAR M.B.M.           1
LICEO SAN JOSE LA PRIMAVERA                                     1
Name: ESTABLECIMIENTO, Length: 162, dtype: int64

#### Variable Departamente

Ciudad Capital tenian sus datos distribuidos de una manera distinta pues la variables DEPARTAMENTO guarda el municipio del establecimiento y la variable MUNICIPIO guarda la zona de la capital en la que recide, así que se crea una variable para reordenar estos datos y volver a la ciudad capital parte de guatemala

In [20]:
#creamos la variable zona para la ciudad capital
df = df.assign(ZONA = lambda x: np.where(x.DEPARTAMENTO == "CIUDAD CAPITAL", x.MUNICIPIO, None))
#volvemos el departamento un municipio 
df = df.assign(MUNICIPIO = lambda x: np.where(x.DEPARTAMENTO == "CIUDAD CAPITAL", x.DEPARTAMENTO, x.MUNICIPIO))
#unimos ciudad capital a guatemala
df = df.assign(DEPARTAMENTO = lambda x: np.where(x.DEPARTAMENTO == "CIUDAD CAPITAL", "GUATEMALA", x.DEPARTAMENTO))

#### Variable dirección

Esta variable tiene diferentes tipos de formatos, decidimos validar direcciones claramente erroneas, constituidas por un par decaracteres invalidos, como "-", "--", "---", ".", "". y las definimos como NONE.

In [21]:
setFaltasDireccion = ['-', '--', '---', '.', ' ', '  ']
df.DIRECCION = df.DIRECCION.replace(setFaltasDireccion, None)

#### Variable Telefono

A muchos numeros telefonicos les faltan numeros, fueron guardados con decimales o inculo algunos establecimientos cuentan con más de un numero telefonico

In [22]:
#i una entrada posee 8 caracteres o más, botamos la cola del dato y nos quedamos con los primeros 8 caracteres. 
# Si es menor a 8 o posee caracteres es desechado

df['TELEFONO'] = df['TELEFONO'].apply(lambda x: str(x))
df['TELEFONO'] = df['TELEFONO'].apply(lambda x: x[0:8] if len(x) >= 8  else None)

#### Variable Director

En algunos establecimientos no aparece quien es el directos y aparecen puntos o caracteres diferentes así que nos cambiamos por NaN

In [24]:
#Contamos las repeticiones de directores
print(df.DIRECTOR.value_counts())

#Convertimos en NaN todos 
df['DIRECTOR']=df['DIRECTOR'].replace('.',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('..',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('...',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('-',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('--',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('---',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('----',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('-----',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('-------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('--------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('---------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('----------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('-----------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('------------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('-------------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('--------------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('---------------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('----------------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('-----------------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('-------------------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('0',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('X',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace(' ',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('SIN DATO',np.NaN)

df.DIRECTOR.value_counts()

MARCO TULIO DE LA CRUZ MORALES    5
JUAN RAX                          5
MAYRA MAGDALENA YAT CHON          5
ERICK FERNANDO CHOC GARCIA        5
ORLEY EDWIN MELENDEZ ROSALES      4
                                 ..
BYRON ANIBAL GOMEZ GATICA         1
JOSE MARIA CHOC                   1
LUIS ANTONIO CHOC CO              1
BENJAMIN JUC BOTZOC               1
JULIO CESAR VILLELA AMADO         1
Name: DIRECTOR, Length: 164, dtype: int64

MARCO TULIO DE LA CRUZ MORALES    5
JUAN RAX                          5
MAYRA MAGDALENA YAT CHON          5
ERICK FERNANDO CHOC GARCIA        5
ORLEY EDWIN MELENDEZ ROSALES      4
                                 ..
BYRON ANIBAL GOMEZ GATICA         1
JOSE MARIA CHOC                   1
LUIS ANTONIO CHOC CO              1
BENJAMIN JUC BOTZOC               1
JULIO CESAR VILLELA AMADO         1
Name: DIRECTOR, Length: 164, dtype: int64

In [28]:
##creamos un csv con los datos limpios
df.to_csv('DatosLimpios.csv')