In [1]:
#librerias a importar
import pandas as pd
import numpy as np

In [14]:
#Se importan los csv de cada uno de los departamentos
ALTA_VERAPAZ = pd.read_csv('ALTA_VERAPAZ.csv')
BAJA_VERAPAZ = pd.read_csv('BAJA_VERAPAZ.csv', encoding='latin-1')
CIUDAD_CAPITAL = pd.read_csv('CIUDAD_CAPITAL.csv')
GUATEMALA = pd.read_csv('GUATEMALA.csv', encoding='latin-1')
CHIMALTENANGO = pd.read_csv('CHIMALTENANGO.csv', encoding='latin-1')
CHIQUIMULA = pd.read_csv('CHIQUIMULA.csv', encoding='latin-1')
EL_PROGRESO = pd.read_csv('EL PROGRESO.csv', encoding='latin-1')
ESCUINTLA = pd.read_csv('ESCUINTLA.csv', encoding='latin-1')
HUEHUETENANGO = pd.read_csv('HUEHUETENANGO.csv', encoding='latin-1')
IZABAL = pd.read_csv('IZABAL.csv', encoding='latin-1')
JALAPA = pd.read_csv('JALAPA.csv', encoding='latin-1')
JUTIAPA = pd.read_csv('JUTIAPA.csv', encoding='latin-1')
PETEN = pd.read_csv('PETEN.csv', encoding='latin-1')
QUETZALTENANGO = pd.read_csv('QUETZALTENANGO.csv', encoding='latin-1')
QUICHE = pd.read_csv('QUICHE.csv', encoding='latin-1')
RETALHULEU = pd.read_csv('RETALHULEU.csv', encoding='latin-1')
SUSHITEPEQUEZ = pd.read_csv('SUCHITEPEQUEZ.csv', encoding='latin-1')
TOTONICAPAN = pd.read_csv('TOTONICAPAN.csv', encoding='latin-1')
ZACAPA = pd.read_csv('ZACAPA.csv', encoding='latin-1')
SACATEPEQUEZ = pd.read_csv('SACATEPEQUEZ.csv',encoding='latin-1')
SOLOLA = pd.read_csv('SOLOLA.csv',encoding='latin-1')
SANMARCOS = pd.read_csv('SANMARCOS.csv',encoding='latin-1')

In [15]:
#Se concatenan todos los dataframes --- agregar los demas departamentos
df = pd.concat([ALTA_VERAPAZ, CIUDAD_CAPITAL, GUATEMALA, CHIMALTENANGO,CHIQUIMULA, EL_PROGRESO, ESCUINTLA, 
                BAJA_VERAPAZ, HUEHUETENANGO, IZABAL, JALAPA, JUTIAPA,PETEN,QUETZALTENANGO,QUICHE,RETALHULEU,
                SUSHITEPEQUEZ,TOTONICAPAN,ZACAPA,SACATEPEQUEZ,SOLOLA,SANMARCOS ], axis=0, ignore_index=True)
df

,CODIGO,DISTRITO,DEPARTAMENTO,MUNICIPIO,ESTABLECIMIENTO,DIRECCION,TELEFONO,SUPERVISOR,DIRECTOR,NIVEL,...,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 0
0,16-01-0138-46,16-031,ALTA VERAPAZ,COBAN,COLEGIO COBAN,KM.2 SALIDA A SAN JUAN CHAMELCO ZONA 8,77945104,MERCEDES JOSEFINA TORRES GALVEZ,JULIO CESAR VILLELA AMADO,DIVERSIFICADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16-01-0139-46,16-031,ALTA VERAPAZ,COBAN,COLEGIO PARTICULAR MIXTO VERAPAZ,KM 209.5 ENTRADA A LA CIUDAD,77367402,MERCEDES JOSEFINA TORRES GALVEZ,---,DIVERSIFICADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16-01-0140-46,16-031,ALTA VERAPAZ,COBAN,"COLEGIO ""LA INMACULADA""",7A. AVENIDA 11-109 ZONA 6,78232301,MERCEDES JOSEFINA TORRES GALVEZ,VIRGINA SOLANO SERRANO,DIVERSIFICADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16-01-0141-46,16-005,ALTA VERAPAZ,COBAN,ESCUELA NACIONAL DE CIENCIAS COMERCIALES,2A CALLE 11-10 ZONA 2,79514215,RUDY ADOLFO TOT OCH,NaN,DIVERSIFICADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16-01-0142-46,16-005,ALTA VERAPAZ,COBAN,INSTITUTO NORMAL MIXTO DEL NORTE 'EMILIO ROSAL...,3A AVE 6-23 ZONA 11,79521468,RUDY ADOLFO TOT OCH,NaN,DIVERSIFICADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,USIELA SARONITA CARRETO LÓPEZ,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,SIN JORNADA,SEMIPRESENCIAL (UN DÍA A LA SEMANA),SAN MARCOS,12-30-0085-46
9023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,BETY PATRICIA OXLAJ PÉREZ,DIVERSIFICADO,PRIVADO,RURAL,CERRADA TEMPORALMENTE,MONOLINGUE,SIN JORNADA,SEMIPRESENCIAL (UN DÍA A LA SEMANA),SAN MARCOS,12-30-0087-46
9024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,MAVERIK GEYSTYNG HURTADO CIFUENTES,DIVERSIFICADO,PRIVADO,URBANA,ABIERTA,MONOLINGUE,SIN JORNADA,SEMIPRESENCIAL (UN DÍA A LA SEMANA),SAN MARCOS,12-30-0089-46
9025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,557 Establecimientos encontrados

In [16]:
#Listamos los nombres de las columnas
list(df.keys())

#Borramos filas duplicadas
df=df.drop_duplicates()

In [17]:
#Observamos la cantidad de na de cada variable
print('CODIGO: ', df['CODIGO'].isna().sum())
print('DISTRITO: ', df['DISTRITO'].isna().sum())
print('DEPARTAMENTO: ', df['DEPARTAMENTO'].isna().sum())
print('MUNICIPIO: ', df['MUNICIPIO'].isna().sum())
print('ESTABLECIMIENTO: ', df['ESTABLECIMIENTO'].isna().sum())
print('DIRECCION: ', df['DIRECCION'].isna().sum())
print('TELEFONO: ', df['TELEFONO'].isna().sum())
print('SUPERVISOR: ', df['SUPERVISOR'].isna().sum())
print('DIRECTOR: ', df['DIRECTOR'].isna().sum())
print('NIVEL: ', df['NIVEL'].isna().sum())
print('SECTOR: ', df['SECTOR'].isna().sum())
print('AREA: ', df['AREA'].isna().sum())
print('STATUS: ', df['STATUS'].isna().sum())
print('MODALIDAD: ', df['MODALIDAD'].isna().sum())
print('JORNADA: ', df['JORNADA'].isna().sum())
print('PLAN: ', df['PLAN'].isna().sum())
print('DEPARTAMENTAL: ', df['DEPARTAMENTAL'].isna().sum())

CODIGO:  702
DISTRITO:  919
DEPARTAMENTO:  722
MUNICIPIO:  722
ESTABLECIMIENTO:  722
DIRECCION:  763
TELEFONO:  1217
SUPERVISOR:  920
DIRECTOR:  1991
NIVEL:  722
SECTOR:  722
AREA:  722
STATUS:  722
MODALIDAD:  722
JORNADA:  722
PLAN:  722
DEPARTAMENTAL:  722

In [18]:
#Botamos todas las filas con valores nulos en el código o establecimiento ya que estas deberían de ser unicas
df=df.dropna(subset = ['CODIGO', 'ESTABLECIMIENTO'])
df

,CODIGO,DISTRITO,DEPARTAMENTO,MUNICIPIO,ESTABLECIMIENTO,DIRECCION,TELEFONO,SUPERVISOR,DIRECTOR,NIVEL,...,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 0
0,16-01-0138-46,16-031,ALTA VERAPAZ,COBAN,COLEGIO COBAN,KM.2 SALIDA A SAN JUAN CHAMELCO ZONA 8,77945104,MERCEDES JOSEFINA TORRES GALVEZ,JULIO CESAR VILLELA AMADO,DIVERSIFICADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16-01-0139-46,16-031,ALTA VERAPAZ,COBAN,COLEGIO PARTICULAR MIXTO VERAPAZ,KM 209.5 ENTRADA A LA CIUDAD,77367402,MERCEDES JOSEFINA TORRES GALVEZ,---,DIVERSIFICADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16-01-0140-46,16-031,ALTA VERAPAZ,COBAN,"COLEGIO ""LA INMACULADA""",7A. AVENIDA 11-109 ZONA 6,78232301,MERCEDES JOSEFINA TORRES GALVEZ,VIRGINA SOLANO SERRANO,DIVERSIFICADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16-01-0141-46,16-005,ALTA VERAPAZ,COBAN,ESCUELA NACIONAL DE CIENCIAS COMERCIALES,2A CALLE 11-10 ZONA 2,79514215,RUDY ADOLFO TOT OCH,NaN,DIVERSIFICADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16-01-0142-46,16-005,ALTA VERAPAZ,COBAN,INSTITUTO NORMAL MIXTO DEL NORTE 'EMILIO ROSAL...,3A AVE 6-23 ZONA 11,79521468,RUDY ADOLFO TOT OCH,NaN,DIVERSIFICADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8317,03-15-0022-46,03-008,SACATEPEQUEZ,SAN ANTONIO AGUAS CALIENTES,INSTITUTO NACIONAL DE EDUCACION DIVERSIFICADA,"6TA. CALLE FINAL 4-81, ZONA 2",7931131,JUAN DEMETRIO SICAJOL PEREZ,EDY PEREZ SINAY,DIVERSIFICADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8318,03-16-0005-46,03-008,SACATEPEQUEZ,SANTA CATARINA BARAHONA,INSTITUTO MUNICIPAL DE EDUCACIÓN BÁSICA Y BACH...,CALLE PRINCIPAL,42645553,JUAN DEMETRIO SICAJOL PEREZ,OSCAR HUMBERTO HERNÁNDEZ LÁZARO,DIVERSIFICADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8319,03-16-0006-46,03-008,SACATEPEQUEZ,SANTA CATARINA BARAHONA,INSTITUTO MUNICIPAL DE EDUCACIÓN BÁSICA Y BACH...,CALLE PRINCIPAL,45707357,JUAN DEMETRIO SICAJOL PEREZ,CLAUDIA JEANETH CHAVEZ FLORES,DIVERSIFICADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8320,03-16-0010-46,03-008,SACATEPEQUEZ,SANTA CATARINA BARAHONA,INSTITUTO MUNICIPAL DE EDUCACION BASICA Y BACH...,CALLE PRINCIPAL SANTA CATARINA BARAHONA,41575081,JUAN DEMETRIO SICAJOL PEREZ,CLAUDIA JEANETH CHAVEZ FLORES,DIVERSIFICADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8321,03-16-1442-46,03-008,SACATEPEQUEZ,SANTA CATARINA BARAHONA,INSTITUTO MUNICIPAL DE EDUCACION BASICA Y BACH...,CALLE PRINCIPAL,NaN,JUAN DEMETRIO SICAJOL PEREZ,NaN,DIVERSIFICADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
#Contamos las repeticiones de establecimientos
df.ESTABLECIMIENTO.value_counts()

INSTITUTO NACIONAL DE EDUCACION DIVERSIFICADA             248
INSTITUTO NACIONAL DE EDUCACIÓN DIVERSIFICADA              69
INSTITUTO DIVERSIFICADO POR COOPERATIVA                    20
ESCUELA NORMAL DE EDUCACION FISICA                         18
INSTITUTO DE COMPUTACION INFORMATICA                       18
                                                         ...
COLEGIO EVANGELICO MIXTO GUATEMALA II                       1
CENTRO DE ESTUDIOS MERCADOLOGICOS Y PUBLICITARIOS CEMP      1
LICEO EDUCATIVO LA ASUNCION                                 1
COLEGIO CAMPOS VERDES                                       1
CENTRO EDUCATIVO MIXTO GUATEMALTECO "CESAR BRAÑAS"          1
Name: ESTABLECIMIENTO, Length: 4833, dtype: int64

In [20]:
#Removemos acentos
cols = df.select_dtypes(include=[object]).columns
df[cols] = df[cols].apply(lambda x: x.str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8'))
df.ESTABLECIMIENTO.value_counts()

INSTITUTO NACIONAL DE EDUCACION DIVERSIFICADA             318
INSTITUTO DE COMPUTACION INFORMATICA                       26
INSTITUTO DIVERSIFICADO POR COOPERATIVA                    20
ESCUELA NORMAL DE EDUCACION FISICA                         18
INSTITUTO GUATEMALTECO DE EDUCACION RADIOFONICA (IGER)     17
                                                         ...
CENTRO CULTURAL AVE MARIA DE LA ASUNCION                    1
COLEGIO ESMERALDA II                                        1
COLEGIO ETAMABAL                                            1
LICEO SAN JOSE DE LOS OLIVOS                                1
CENTRO EDUCATIVO MIXTO GUATEMALTECO "CESAR BRANAS"          1
Name: ESTABLECIMIENTO, Length: 4498, dtype: int64

#### Variable Departamento

Ciudad Capital tenian sus datos distribuidos de una manera distinta pues la variables DEPARTAMENTO guarda el municipio del establecimiento y la variable MUNICIPIO guarda la zona de la capital en la que recide, así que se crea una variable para reordenar estos datos y volver a la ciudad capital parte de guatemala

In [21]:
#creamos la variable zona para la ciudad capital
df = df.assign(ZONA = lambda x: np.where(x.DEPARTAMENTO == "CIUDAD CAPITAL", x.MUNICIPIO, None))
#volvemos el departamento un municipio 
df = df.assign(MUNICIPIO = lambda x: np.where(x.DEPARTAMENTO == "CIUDAD CAPITAL", x.DEPARTAMENTO, x.MUNICIPIO))
#unimos ciudad capital a guatemala
df = df.assign(DEPARTAMENTO = lambda x: np.where(x.DEPARTAMENTO == "CIUDAD CAPITAL", "GUATEMALA", x.DEPARTAMENTO))

#### Variable dirección

Esta variable tiene diferentes tipos de formatos, decidimos validar direcciones claramente erroneas, constituidas por un par decaracteres invalidos, como "-", "--", "---", ".", "". y las definimos como NONE.

In [22]:
setFaltasDireccion = ['-', '--', '---', '.', ' ', '  ']
df.DIRECCION = df.DIRECCION.replace(setFaltasDireccion, None)

In [23]:
#i una entrada posee 8 caracteres o más, botamos la cola del dato y nos quedamos con los primeros 8 caracteres. 
# Si es menor a 8 o posee caracteres es desechado

df['TELEFONO'] = df['TELEFONO'].apply(lambda x: str(x))
df['TELEFONO'] = df['TELEFONO'].apply(lambda x: x[0:8] if len(x) >= 8  else None)

#### Variable Director

En algunos establecimientos no aparece quien es el directos y aparecen puntos o caracteres diferentes así que nos cambiamos por NaN

In [24]:
#Contamos las repeticiones de directores
print(df.DIRECTOR.value_counts())

#Convertimos en NaN todos 
df['DIRECTOR']=df['DIRECTOR'].replace('.',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('..',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('...',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('-',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('--',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('---',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('----',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('-----',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('-------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('--------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('---------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('----------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('-----------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('------------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('-------------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('--------------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('---------------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('----------------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('-----------------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('-------------------',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('0',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('X',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace(' ',np.NaN)
df['DIRECTOR']=df['DIRECTOR'].replace('SIN DATO',np.NaN)

df.DIRECTOR.value_counts()

---                                     172
--                                       62
.                                        41
----                                     38
-----                                    26
                                       ...
WALFRE RIGOBERTO MERIDA ALVA              1
MATEO GOMEZ GOMEZ                         1
INGRID LINETT MENDOZA RODRIGUEZ           1
CLAUDIA JEANNETTE PALACIOS HERNANDEZ      1
JULIO CESAR VILLELA AMADO                 1
Name: DIRECTOR, Length: 4120, dtype: int64

JORGE GRANADOS GUZMAN                13
IRIS MARICLO MORALES LUNA            12
MARIA DOLORES PEREZ TUCHAN           11
CRISTIAN ALEXANDER PEREZ GONZALEZ     9
MELVIN RAFAEL REYES LOPEZ             9
                                     ..
OSCAR LEONEL PAIZ DEL CID             1
MIRIAM ANDREA VILLEDA                 1
HEBER MERARY ECHEVERRIA CASTANEDA     1
EDVIN JAVIER ESPANA CHACON            1
MARIA PATRICIA ARRIOLA FERNANDEZ      1
Name: DIRECTOR, Length: 4096, dtype: int64

In [25]:
##creamos un csv con los datos limpios
df.to_csv('DatosLimpios.csv')